### ISSUE TITLE
Please add installation information/tutorial for non-bundle users

### ISSUE THREAD

**Issue by 0rbiter** [gilligan/vim-lldb#15]
lldb.vim is in ~/.vim/plugin/
copied python-vim-lldb to ~/.vim/
lldb.txt is in ~/.vim/doc/
lldb is installed
which lldb -> /usr/bin/lldb
created env variable LLDB=/usr/bin/lldb

Error message:
Error loading lldb module; vim-lldb will be disabled. Check LLDB installation or set LLDB environment variable.
Error detected while processing function <SNR>8_InitLldbPlugin..lldb#pythonInit:
line    4:
Unable to load vim/lldb module. Check lldb is on the path is available (or LLDB is set) and that script is invoked inside Vim with :pyfile

**Comment by gilligan** [comment]
I am really sorry but I stopped doing any C/C++ programming years ago and also don't use/update this plugin anymore. 

Would be cool if anyone wanted to take over though..

**Comment by 0rbiter** [comment]
kk
